In [2]:
import pandas as pd
import numpy as np
import random
import pickle

In [3]:
df2 = pd.read_csv('/Users/shashankshivam/Desktop/dissertationfinalmarks1.csv')
df2.head()

Unnamed: 0  maths  comp  ba  states  chemistry  physics  history  politics  \
0           0     89    97  50      55         41       60        0         0   
1           1     94    94  53      54         42       41        0         0   
2           2     77    83  41      61         50       61        0         0   
3           3     87    99  49      47         51       58        0         0   
4           4     88    77  41      55         51       45        0         0   

   economics  english  biology field  
0         49       72        0    IT  
1         45       68        0    IT  
2         48       71        0    IT  
3         59       55        0    IT  
4         43       50        0    IT

In [4]:
df2['field'].replace("IT",1,inplace=True)
df2['field'].replace("managment",2,inplace=True)
df2['field'].replace("Medical",3,inplace=True)
df2['field'].replace("political_science",4,inplace=True)
df2['field'].replace("others",5,inplace=True)

In [5]:
X=df2.drop(['field'],1)
X=X.values

In [6]:
y=df2['field']
y=y.values

In [7]:
import sklearn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
from sklearn import svm
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import accuracy_score

model = svm.SVC(kernel = "rbf")
model.fit(X_train, y_train)
pred_y = model.predict(X_test)
print(metrics.classification_report(y_test, pred_y))
print(metrics.confusion_matrix(y_test,pred_y))
print(accuracy_score(y_test, pred_y))
svm_score=accuracy_score(y_test, pred_y)

              precision    recall  f1-score   support

           1       0.00      0.00      0.00        88
           2       0.00      0.00      0.00       107
           3       0.25      1.00      0.41       126
           4       0.00      0.00      0.00        76
           5       0.00      0.00      0.00        98

    accuracy                           0.25       495
   macro avg       0.05      0.20      0.08       495
weighted avg       0.06      0.25      0.10       495

[[  0   0  88   0   0]
 [  0   0 107   0   0]
 [  0   0 126   0   0]
 [  0   0  76   0   0]
 [  0   0  98   0   0]]
0.2545454545454545


/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score 
model = LogisticRegression()
model.fit(X_test,y_test)
predicted_classes = model.predict(X_test)
accuracy = accuracy_score(y_test,predicted_classes)
#accuracy*100

print(metrics.classification_report(y_test, predicted_classes))
print(metrics.confusion_matrix(y_test,predicted_classes))
print(accuracy_score(y_test, predicted_classes))

              precision    recall  f1-score   support

           1       0.87      0.84      0.86        88
           2       0.87      0.90      0.88       107
           3       1.00      1.00      1.00       126
           4       1.00      1.00      1.00        76
           5       1.00      1.00      1.00        98

    accuracy                           0.95       495
   macro avg       0.95      0.95      0.95       495
weighted avg       0.95      0.95      0.95       495

[[ 74  14   0   0   0]
 [ 11  96   0   0   0]
 [  0   0 126   0   0]
 [  0   0   0  76   0]
 [  0   0   0   0  98]]
0.9494949494949495


/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [9]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)
prediction = model.predict(X_test)

print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test,prediction))
print(accuracy_score(y_test, prediction))
accuracy_score(y_test,prediction)*100

              precision    recall  f1-score   support

           1       0.73      0.94      0.83        88
           2       0.94      0.72      0.81       107
           3       1.00      1.00      1.00       126
           4       1.00      1.00      1.00        76
           5       1.00      1.00      1.00        98

    accuracy                           0.93       495
   macro avg       0.93      0.93      0.93       495
weighted avg       0.94      0.93      0.93       495

[[ 83   5   0   0   0]
 [ 30  77   0   0   0]
 [  0   0 126   0   0]
 [  0   0   0  76   0]
 [  0   0   0   0  98]]
0.9292929292929293


92.92929292929293

In [10]:
from sklearn.tree import DecisionTreeClassifier 
from sklearn import metrics

In [11]:
clf = DecisionTreeClassifier()

In [12]:
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [13]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9252525252525252


In [14]:
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test, y_pred))
accuracy_score(y_test,y_pred)*100

              precision    recall  f1-score   support

           1       0.77      0.83      0.80        88
           2       0.85      0.79      0.82       107
           3       1.00      1.00      1.00       126
           4       1.00      1.00      1.00        76
           5       1.00      1.00      1.00        98

    accuracy                           0.93       495
   macro avg       0.92      0.92      0.92       495
weighted avg       0.93      0.93      0.93       495

[[ 73  15   0   0   0]
 [ 22  85   0   0   0]
 [  0   0 126   0   0]
 [  0   0   0  76   0]
 [  0   0   0   0  98]]
0.9252525252525252


92.52525252525253

In [15]:
pickle.dump(model, open('model.pkl','wb'))

In [16]:
model = pickle.load(open('model.pkl','rb'))