In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [25]:
df = pd.read_csv('/Users/shashankshivam/Desktop/dissertationfinalmarks1.csv')

In [26]:
df.head()

Unnamed: 0  maths  comp  ba  states  chemistry  physics  history  politics  \
0           0     89    97  50      55         41       60        0         0   
1           1     94    94  53      54         42       41        0         0   
2           2     77    83  41      61         50       61        0         0   
3           3     87    99  49      47         51       58        0         0   
4           4     88    77  41      55         51       45        0         0   

   economics  english  biology field  
0         49       72        0    IT  
1         45       68        0    IT  
2         48       71        0    IT  
3         59       55        0    IT  
4         43       50        0    IT

In [27]:
df.shape

(1500, 13)

In [28]:
df = df.drop('Unnamed: 0',axis=1)

In [29]:
df.shape

(1500, 12)

In [30]:
df['field'].replace("IT",1,inplace=True)
df['field'].replace("managment",2,inplace=True)
df['field'].replace("Medical",3,inplace=True)
df['field'].replace("political_science",4,inplace=True)
df['field'].replace("others",5,inplace=True)

In [31]:
X=df.drop(['field'],1)
X=X.values

In [32]:
y=df['field']
y=y.values

In [33]:
X

array([[89, 97, 50, ..., 49, 72,  0],
       [94, 94, 53, ..., 45, 68,  0],
       [77, 83, 41, ..., 48, 71,  0],
       ...,
       [48, 40, 43, ..., 47, 45,  0],
       [47, 48, 44, ..., 42, 45,  0],
       [42, 45, 49, ..., 43, 43,  0]])

In [34]:
y

array([1, 1, 1, ..., 5, 5, 5])

In [35]:
# import sklearn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
# from sklearn import svm
# from sklearn.svm import SVC
# from sklearn import metrics
# from sklearn.metrics import accuracy_score

In [36]:
# model = svm.SVC(kernel = "rbf")
# model.fit(X_train, y_train)

In [37]:
# pred_y = model.predict(X_test)
# print(metrics.classification_report(y_test, pred_y))
# print(metrics.confusion_matrix(y_test,pred_y))
# print(accuracy_score(y_test, pred_y))
# svm_score=accuracy_score(y_test, pred_y)

In [38]:
# from sklearn.linear_model import LogisticRegression
# from sklearn.metrics import accuracy_score 
# model = LogisticRegression()
# model.fit(X_test,y_test)
# predicted_classes = model.predict(X_test)
# accuracy = accuracy_score(y_test,predicted_classes)
# #accuracy*100

# print(metrics.classification_report(y_test, predicted_classes))
# print(metrics.confusion_matrix(y_test,predicted_classes))
# print(accuracy_score(y_test, predicted_classes))

In [39]:
# from sklearn.naive_bayes import GaussianNB
# model = GaussianNB()
# model.fit(X_train,y_train)
# prediction = model.predict(X_test)


# print(metrics.classification_report(y_test, prediction))
# print(metrics.confusion_matrix(y_test,prediction))
# print(accuracy_score(y_test, prediction))
# accuracy_score(y_test,prediction)*100

In [17]:
#X_test[1]

In [40]:
t=np.array([89,90,54,56,67,56,45,65,56,67,45])
t

array([89, 90, 54, 56, 67, 56, 45, 65, 56, 67, 45])

In [19]:
#t=np.array(np.random.randint(10,50,11))

In [20]:
#t=t.reshape(-1,1)

In [21]:
t

array([89, 90, 54, 56, 67, 56, 45, 65, 56, 67, 45])

In [41]:
t=t.reshape(1,-1)
t

array([[89, 90, 54, 56, 67, 56, 45, 65, 56, 67, 45]])

In [46]:
#import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = gnb.predict(np.array([[45, 40, 74, 76, 77, 76, 85, 85, 86, 87, 85]]))
print(y_pred)

[4]


In [86]:
pickle.dump(model, open('backend.pkl','wb'))

In [87]:
t

array([[62, 71, 40, 47, 42, 34, 89, 92, 25, 41,  0]])

In [88]:
model = pickle.load(open('model.pkl','rb'))
print(model.predict(t))

ValueError: operands could not be broadcast together with shapes (1,11) (12,) 