In [1]:
import numpy as np
import pandas as pd
import pickle

In [2]:
df = pd.read_csv('/Users/shashankshivam/Desktop/finalmarks.csv')

In [3]:
df.shape

(3440, 26)

In [4]:
df.head()

Unnamed: 0  accounts  ba  biology  chemistry  comp  economics  english  \
0           0      58.0  48     47.0       50.0    45       53.0     55.0   
1           1      58.0  46     55.0       53.0    45       51.0     50.0   
2           2      59.0  54     47.0       57.0    50       40.0     55.0   
3           3      52.0  52     41.0       45.0    56       45.0     49.0   
4           4      58.0  41     56.0       45.0    44       43.0     46.0   

   field  history  ...  q12     q2   q3   q4   q5   q6   q7   q8   q9  stats  
0    3.0     50.0  ...  0.0  100.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     58  
1    3.0     56.0  ...  0.0  100.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     49  
2    3.0     40.0  ...  0.0  100.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     50  
3    3.0     49.0  ...  0.0  100.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     41  
4    3.0     41.0  ...  0.0  100.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     52  

[5 rows x 26 columns]

In [5]:
df.groupby('field').count()

Unnamed: 0  accounts    ba  biology  chemistry  comp  economics  \
field                                                                    
1.0           520       520   520      520        520   520        520   
2.0           487       487   487      487        487   487        487   
3.0           547       547   547      547        547   547        547   
4.0          1015      1015  1015     1015       1015  1015       1015   
5.0           270       270   270      270        270   270        270   
6.0           601       601   601      601        601   601        601   

       english  history  maths  ...   q12    q2    q3    q4    q5    q6    q7  \
field                           ...                                             
1.0        520      520    520  ...   520   520   520   520   520   520   520   
2.0        487      487    487  ...   487   487   487   487   487   487   487   
3.0        547      547    547  ...   547   547   547   547   547   547   547   
4.0       1015     1015   1015  ...  1015  1015  1015  1015  1015  1015  1015   
5.0        270      270    270  ...   270   270   270   270   270   270   270   
6.0        601      601    601  ...   601   601   601   601   601   601   601   

         q8    q9  stats  
field                     
1.0     520   520    520  
2.0     487   487    487  
3.0     547   547    547  
4.0    1015  1015   1015  
5.0     270   270    270  
6.0     601   601    601  

[6 rows x 25 columns]

In [6]:
df = df.drop('Unnamed: 0',axis=1)

In [7]:
df.head()

accounts  ba  biology  chemistry  comp  economics  english  field  history  \
0      58.0  48     47.0       50.0    45       53.0     55.0    3.0     50.0   
1      58.0  46     55.0       53.0    45       51.0     50.0    3.0     56.0   
2      59.0  54     47.0       57.0    50       40.0     55.0    3.0     40.0   
3      52.0  52     41.0       45.0    56       45.0     49.0    3.0     49.0   
4      58.0  41     56.0       45.0    44       43.0     46.0    3.0     41.0   

   maths  ...  q12     q2   q3   q4   q5   q6   q7   q8   q9  stats  
0     59  ...  0.0  100.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     58  
1     57  ...  0.0  100.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     49  
2     50  ...  0.0  100.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     50  
3     49  ...  0.0  100.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     41  
4     41  ...  0.0  100.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     52  

[5 rows x 25 columns]

In [8]:
X=df.drop(['field'],1)
X=X.values
y=df['field']
y=y.values

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [10]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score 
from sklearn import metrics
model = GaussianNB()
model.fit(X_train,y_train)
prediction = model.predict(X_test)

print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test,prediction))
print(accuracy_score(y_test, prediction))
accuracy_score(y_test,prediction)*100

              precision    recall  f1-score   support

         1.0       0.81      0.68      0.74       182
         2.0       0.91      0.73      0.81       168
         3.0       0.88      0.59      0.71       177
         4.0       0.99      0.59      0.74       318
         5.0       0.18      0.96      0.30        78
         6.0       0.97      0.53      0.69       213

    accuracy                           0.64      1136
   macro avg       0.79      0.68      0.66      1136
weighted avg       0.88      0.64      0.71      1136

[[123   0   7   0  52   0]
 [  9 123   0   0  34   2]
 [ 14   0 105   0  57   1]
 [  0   2   5 188 123   0]
 [  1   0   1   1  75   0]
 [  5  10   1   0  84 113]]
0.6399647887323944


63.99647887323944

In [14]:
t=np.array(np.random.randint(40,101,24))
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)
prediction = model.predict(t.reshape(1,-1))

pickle.dump(model, open('finalmodel.pkl','wb'))

# Loading model to compare the results
model = pickle.load(open('finalmodel.pkl','rb'))
prediction=model.predict(t.reshape(1,-1))
prediction[0]

2.0