In [187]:
import pandas as pd
import numpy as np
import random

In [188]:
df=pd.DataFrame()  #it---g
df1=pd.DataFrame() #m----g
df3=pd.DataFrame() #it---av 
df4=pd.DataFrame() #m----av
df5=pd.DataFrame() #it---p
df6=pd.DataFrame() #m----p
df7=pd.DataFrame() #med---g--c
df8=pd.DataFrame() #med---g--eco
df9=pd.DataFrame() #med--av
df10=pd.DataFrame() #med--av--eco
df11=pd.DataFrame() #poli --g
df12=pd.DataFrame() #poli--avg
df13=pd.DataFrame() #others 


In [189]:
df['maths']=np.random.randint(75,101,200)
df['comp']=np.random.randint(75,101,200)
df['ba']=np.random.randint(40,55,200)
df['states']=np.random.randint(40,67,200)
df['chemistry']=np.random.randint(40,60,200)
df['physics']=np.random.randint(40,65,200)
df['history']=np.random.randint(40,60,200)
df['politics']=np.random.randint(40,60,200)
df['economics']=np.random.randint(40,60,200)
df['english']=np.random.randint(45,75,200)
df['biology']=np.random.randint(40,60,200)
df['field']='IT'

In [190]:
df3['maths']=np.random.randint(60,75,50)
df3['comp']=np.random.randint(60,75,50)
#df['interest']='problem_solving'
df3['ba']=np.random.randint(60,75,50)
df3['states']=np.random.randint(60,75,50)
df3['chemistry']=np.random.randint(60,75,50)
df3['physics']=np.random.randint(60,75,50)
df3['history']=0
df3['politics']=0
df3['economics']=np.random.randint(60,75,50)
df3['english']=np.random.randint(60,75,50)
df3['biology']=np.random.randint(40,55,50)
df3['field']='IT'

In [191]:
df5['maths']=np.random.randint(40,55,50)
df5['comp']=np.random.randint(40,55,50)
#df['interest']='problem_solving'
df5['ba']=np.random.randint(40,55,50)
df5['states']=np.random.randint(40,55,50)
df5['chemistry']=np.random.randint(40,55,50)
df5['physics']=np.random.randint(40,55,50)
df5['history']=0
df5['politics']=0
df5['economics']=np.random.randint(40,55,50)
df5['english']=np.random.randint(40,55,50)
df5['biology']=np.random.randint(40,55,50)
df5['field']='IT'

In [192]:
df1['maths']=np.random.randint(75,101,200)
df1['comp']=np.random.randint(75,101,200)
#df['interest']='problem_solving'
df1['ba']=np.random.randint(40,55,200)
df1['states']=np.random.randint(40,67,200)
df1['chemistry']=0
df1['physics']=0
df1['history']=0
df1['politics']=0
df1['economics']=np.random.randint(75,101,200)
df1['english']=np.random.randint(75,101,200)
df1['biology']=np.random.randint(40,55,200)
df1['field']='managment'

In [193]:
df4['maths']=np.random.randint(60,75,50)
df4['comp']=np.random.randint(60,75,50)
#df['interest']='problem_solving'
df4['ba']=np.random.randint(60,75,50)
df4['states']=np.random.randint(60,75,50)
df4['chemistry']=np.random.randint(60,75,50)
df4['physics']=np.random.randint(60,75,50)
df4['history']=0
df4['politics']=0
df4['economics']=np.random.randint(60,75,50)
df4['english']=np.random.randint(60,75,50)
df4['biology']=np.random.randint(40,55,50)
df4['field']='managment'

In [194]:
df6['maths']=np.random.randint(40,55,50)
df6['comp']=np.random.randint(40,55,50)
#df['interest']='problem_solving'
df6['ba']=np.random.randint(40,55,50)
df6['states']=np.random.randint(40,55,50)
df6['chemistry']=np.random.randint(40,55,50)
df6['physics']=np.random.randint(40,55,50)
df6['history']=0
df6['politics']=0
df6['economics']=np.random.randint(40,55,50)
df6['english']=np.random.randint(40,55,50)
df6['biology']=np.random.randint(40,55,50)
df6['field']='managment'

In [195]:
#df7 = pd.DataFrame()
df7['maths']=np.random.randint(40,60,200)
df7['comp']=np.random.randint(40,60,200)
#df['interest']='problem_solving'
df7['ba']=0
df7['states']=np.random.randint(40,60,200)
df7['chemistry']=np.random.randint(65,101,200)
df7['physics']=np.random.randint(65,101,200)
df7['history']=0
df7['politics']=0
df7['economics']=np.random.randint(75,101,200)
df7['english']=np.random.randint(75,101,200)
df7['biology']=np.random.randint(75,101,200)
df7['field']='Medical'
df7.head()

maths  comp  ba  states  chemistry  physics  history  politics  economics  \
0     52    52   0      55         71       68        0         0         79   
1     43    58   0      54         93       77        0         0         93   
2     42    51   0      43         71       69        0         0         82   
3     54    45   0      58         86       75        0         0         85   
4     56    56   0      53         71       99        0         0         93   

   english  biology    field  
0       79       87  Medical  
1       86       82  Medical  
2       77       99  Medical  
3       86       75  Medical  
4       79       87  Medical

In [196]:
df8['maths']=np.random.randint(40,50,50)
df8['comp']=np.random.randint(40,50,50)
df8['ba']=0
df8['states']=np.random.randint(45,60,50)
df8['chemistry']=np.random.randint(60,75,50)
df8['physics']=np.random.randint(60,75,50)
df8['history']=0
df8['politics']=0
df8['economics']=np.random.randint(40,50,50)
df8['english']=np.random.randint(60,75,50)
df8['biology']=np.random.randint(60,75,50)
df8['field']='Medical'
df8.head()

maths  comp  ba  states  chemistry  physics  history  politics  economics  \
0     44    43   0      47         70       65        0         0         40   
1     46    41   0      59         74       67        0         0         41   
2     48    40   0      55         71       64        0         0         40   
3     43    41   0      59         68       62        0         0         46   
4     44    42   0      55         74       71        0         0         41   

   english  biology    field  
0       63       66  Medical  
1       67       68  Medical  
2       71       61  Medical  
3       71       73  Medical  
4       66       72  Medical

In [197]:
df9['maths']=np.random.randint(40,50,50)
df9['comp']=np.random.randint(40,50,50)
df9['ba']=0
df9['states']=np.random.randint(45,50,50)
df9['chemistry']=np.random.randint(40,55,50)
df9['physics']=np.random.randint(40,55,50)
df9['history']=0
df9['politics']=0
df9['economics']=np.random.randint(40,50,50)
df9['english']=np.random.randint(40,55,50)
df9['biology']=np.random.randint(40,59,50)
df9['field']='Medical'
df9.head()

maths  comp  ba  states  chemistry  physics  history  politics  economics  \
0     44    46   0      47         54       46        0         0         49   
1     41    43   0      48         44       43        0         0         48   
2     48    45   0      45         53       44        0         0         47   
3     47    41   0      47         45       53        0         0         42   
4     44    43   0      46         44       52        0         0         40   

   english  biology    field  
0       41       52  Medical  
1       45       52  Medical  
2       44       51  Medical  
3       51       58  Medical  
4       53       58  Medical

In [198]:
df2 = pd.concat([df,df1,df3,df4,df5,df6,df7,df8,df9])

In [199]:
df2.head()

maths  comp  ba  states  chemistry  physics  history  politics  economics  \
0     87    82  48      65         55       43        0         0         50   
1     94    80  52      52         59       63        0         0         52   
2     83    78  41      53         43       45        0         0         50   
3     98    80  45      62         54       63        0         0         49   
4     78    77  52      45         40       60        0         0         54   

   english  biology field  
0       74       44    IT  
1       50       42    IT  
2       46       45    IT  
3       45       41    IT  
4       55       42    IT

In [200]:
df2['field'].replace("IT",1,inplace=True)
df2['field'].replace("managment",2,inplace=True)
df2['field'].replace("Medical",3,inplace=True)
df2
df2.describe()
df2.groupby('field').count()

maths  comp   ba  states  chemistry  physics  history  politics  \
field                                                                    
1        300   300  300     300        300      300      300       300   
2        300   300  300     300        300      300      300       300   
3        300   300  300     300        300      300      300       300   

       economics  english  biology  
field                               
1            300      300      300  
2            300      300      300  
3            300      300      300

In [220]:
df2 = pd.read_csv('/Users/shashankshivam/Desktop/dissertationfinalmarks1.csv')
df2.head()

Unnamed: 0  maths  comp  ba  states  chemistry  physics  history  politics  \
0           0     89    97  50      55         41       60        0         0   
1           1     94    94  53      54         42       41        0         0   
2           2     77    83  41      61         50       61        0         0   
3           3     87    99  49      47         51       58        0         0   
4           4     88    77  41      55         51       45        0         0   

   economics  english  biology field  
0         49       72        0    IT  
1         45       68        0    IT  
2         48       71        0    IT  
3         59       55        0    IT  
4         43       50        0    IT

In [221]:
df2['field'].replace("IT",1,inplace=True)
df2['field'].replace("managment",2,inplace=True)
df2['field'].replace("Medical",3,inplace=True)
df2['field'].replace("political_science",4,inplace=True)
df2['field'].replace("others",5,inplace=True)

In [212]:
from sklearn.utils import shuffle
df2= shuffle(df2)

In [222]:
X=df2.drop(['field'],1)
X=X.values

In [223]:
y=df2['field']
y=y.values

In [224]:
import sklearn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
from sklearn import svm
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import accuracy_score

In [225]:
model = svm.SVC(kernel = "rbf")
model.fit(X_train, y_train)
pred_y = model.predict(X_test)
print(metrics.classification_report(y_test, pred_y))
print(metrics.confusion_matrix(y_test,pred_y))
print(accuracy_score(y_test, pred_y))
svm_score=accuracy_score(y_test, pred_y)

              precision    recall  f1-score   support

           1       0.00      0.00      0.00        88
           2       0.00      0.00      0.00       107
           3       0.25      1.00      0.41       126
           4       0.00      0.00      0.00        76
           5       0.00      0.00      0.00        98

    accuracy                           0.25       495
   macro avg       0.05      0.20      0.08       495
weighted avg       0.06      0.25      0.10       495

[[  0   0  88   0   0]
 [  0   0 107   0   0]
 [  0   0 126   0   0]
 [  0   0  76   0   0]
 [  0   0  98   0   0]]
0.2545454545454545


/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [226]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score 
model = LogisticRegression()
model.fit(X_test,y_test)
predicted_classes = model.predict(X_test)
accuracy = accuracy_score(y_test,predicted_classes)
#accuracy*100

print(metrics.classification_report(y_test, predicted_classes))
print(metrics.confusion_matrix(y_test,predicted_classes))
print(accuracy_score(y_test, predicted_classes))

              precision    recall  f1-score   support

           1       0.87      0.84      0.86        88
           2       0.87      0.90      0.88       107
           3       1.00      1.00      1.00       126
           4       1.00      1.00      1.00        76
           5       1.00      1.00      1.00        98

    accuracy                           0.95       495
   macro avg       0.95      0.95      0.95       495
weighted avg       0.95      0.95      0.95       495

[[ 74  14   0   0   0]
 [ 11  96   0   0   0]
 [  0   0 126   0   0]
 [  0   0   0  76   0]
 [  0   0   0   0  98]]
0.9494949494949495


/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [227]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)
prediction = model.predict(X_test)

print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test,prediction))
print(accuracy_score(y_test, prediction))
accuracy_score(y_test,prediction)*100

              precision    recall  f1-score   support

           1       0.73      0.94      0.83        88
           2       0.94      0.72      0.81       107
           3       1.00      1.00      1.00       126
           4       1.00      1.00      1.00        76
           5       1.00      1.00      1.00        98

    accuracy                           0.93       495
   macro avg       0.93      0.93      0.93       495
weighted avg       0.94      0.93      0.93       495

[[ 83   5   0   0   0]
 [ 30  77   0   0   0]
 [  0   0 126   0   0]
 [  0   0   0  76   0]
 [  0   0   0   0  98]]
0.9292929292929293


92.92929292929293