In [22]:
import pandas as pd
import numpy as np
import random

In [23]:
df=pd.DataFrame()  #it---g
df1=pd.DataFrame() #m----g
df3=pd.DataFrame() #it---av 
df4=pd.DataFrame() #m----av
df5=pd.DataFrame() #it---p
df6=pd.DataFrame() #m----p
df7=pd.DataFrame() #med---g--c
df8=pd.DataFrame() #med---g--eco
df9=pd.DataFrame() #med--av
df10=pd.DataFrame() #med--av--eco
df11=pd.DataFrame() #poli --g
df12=pd.DataFrame() #poli--avg
df13=pd.DataFrame() #others 

## Technical

In [24]:
df['maths']=np.random.randint(75,101,300)
df['comp']=np.random.randint(75,101,300)
df['ba']=np.random.randint(40,55,300)
df['stats']=np.random.randint(75,101,300)
df['chemistry']=np.random.randint(40,60,300)
df['physics']=np.random.randint(75,101,300)
df['history']=np.random.randint(40,60,300)
df['politics']=np.random.randint(40,60,300)
df['economics']=np.random.randint(40,60,300)
df['english']=np.random.randint(45,75,300)
df['biology']=np.random.randint(40,60,300)
df['q1']=100
df['q2']=100
df['q3']=100
for x in ['q4','q5','q6','q7','q8','q9','q10','q11','q12','q13','q14','q15','q16','q17','q18']:
    df[x]=0
    
df['field']='Technical'

In [25]:
df.head()

maths  comp  ba  stats  chemistry  physics  history  politics  economics  \
0     94    96  51     85         46       90       46        53         48   
1     97    97  44     79         55       81       51        42         57   
2     96    75  43     96         52       80       49        48         53   
3     80   100  49     94         56       90       49        41         52   
4     91    81  45     87         49       99       50        45         52   

   english  ...  q10  q11  q12  q13  q14  q15  q16  q17  q18      field  
0       66  ...    0    0    0    0    0    0    0    0    0  Technical  
1       62  ...    0    0    0    0    0    0    0    0    0  Technical  
2       69  ...    0    0    0    0    0    0    0    0    0  Technical  
3       73  ...    0    0    0    0    0    0    0    0    0  Technical  
4       51  ...    0    0    0    0    0    0    0    0    0  Technical  

[5 rows x 30 columns]

In [26]:
df1['maths']=np.random.randint(50,70,10)
df1['comp']=np.random.randint(50,75,10)
df1['ba']=np.random.randint(50,75,10)
df1['stats']=np.random.randint(50,70,10)
df1['chemistry']=np.random.randint(50,70,10)
df1['physics']=np.random.randint(40,70,10)
df1['history']=np.random.randint(60,70,10)
df1['politics']=np.random.randint(40,50,10)
df1['economics']=np.random.randint(40,50,10)
df1['english']=np.random.randint(45,50,10)
df1['biology']=np.random.randint(40,60,10)
df1['q1']=0
df1['q2']=100
df1['q3']=100
for x in ['q4','q5','q6','q7','q8','q9','q10','q11','q12','q13','q14','q15','q16','q17','q18']:
    df1[x]=0
    
df1['field']='Technical'

In [31]:
df1=pd.DataFrame()
df1['maths']=np.random.randint(50,70,20)
df1['comp']=np.random.randint(50,75,20)
df1['ba']=np.random.randint(50,75,20)
df1['stats']=np.random.randint(50,70,20)
df1['chemistry']=np.random.randint(50,70,20)
df1['physics']=np.random.randint(40,70,20)
df1['history']=np.random.randint(60,70,20)
df1['politics']=np.random.randint(40,50,20)
df1['economics']=np.random.randint(40,50,20)
df1['english']=np.random.randint(45,50,20)
df1['biology']=np.random.randint(40,60,20)
df1['q1']=100
df1['q2']=100
df1['q3']=0
for x in ['q4','q5','q6','q7','q8','q9','q10','q11','q12','q13','q14','q15','q16','q17','q18']:
    df1[x]=0
    
df1['field']='Technical'

In [38]:
#technical=pd.concat([technical,df1])
technical.head()

maths  comp  ba  stats  chemistry  physics  history  politics  economics  \
0     94    96  51     85         46       90       46        53         48   
1     97    97  44     79         55       81       51        42         57   
2     96    75  43     96         52       80       49        48         53   
3     80   100  49     94         56       90       49        41         52   
4     91    81  45     87         49       99       50        45         52   

   english  ...  q11  q12  q13  q14  q15  q16  q17  q18      field  accounts  
0       66  ...    0    0    0    0    0    0    0    0  Technical        58  
1       62  ...    0    0    0    0    0    0    0    0  Technical        57  
2       69  ...    0    0    0    0    0    0    0    0  Technical        53  
3       73  ...    0    0    0    0    0    0    0    0  Technical        59  
4       51  ...    0    0    0    0    0    0    0    0  Technical        40  

[5 rows x 31 columns]

## Management

In [71]:
df = pd.DataFrame()
df['maths']=np.random.randint(40,65,300)
df['comp']=np.random.randint(40,65,300)
df['ba']=np.random.randint(75,101,300)
df['stats']=np.random.randint(40,65,300)
df['chemistry']=np.random.randint(40,60,300)
df['physics']=np.random.randint(40,60,300)
df['history']=np.random.randint(40,60,300)
df['politics']=np.random.randint(40,60,300)
df['economics']=np.random.randint(75,101,300)
df['english']=np.random.randint(45,70,300)
df['biology']=np.random.randint(40,60,300)
df['q4']=100
df['q5']=100
df['q6']=100
for x in ['q1','q2','q3','q7','q8','q9','q10','q11','q12','q13','q14','q15','q16','q17','q18']:
    df[x]=0
    
df['field']='Management'
df['accounts']=np.random.randint(75,101,300)

In [72]:
df1=pd.DataFrame()
df1['maths']=np.random.randint(50,60,20)
df1['comp']=np.random.randint(50,65,20)
df1['ba']=np.random.randint(50,75,20)
df1['stats']=np.random.randint(50,70,20)
df1['chemistry']=np.random.randint(50,60,20)
df1['physics']=np.random.randint(40,60,20)
df1['history']=np.random.randint(60,70,20)
df1['politics']=np.random.randint(40,50,20)
df1['economics']=np.random.randint(50,70,20)
df1['english']=np.random.randint(45,50,20)
df1['biology']=np.random.randint(40,60,20)
df1['q4']=0
df1['q5']=100
df1['q6']=100
for x in ['q1','q2','q3','q7','q8','q9','q10','q11','q12','q13','q14','q15','q16','q17','q18']:
    df1[x]=0
    
df1['field']='Management'
df1['accounts']=np.random.randint(50,60,20)

In [74]:
df1=pd.DataFrame()
df1['maths']=np.random.randint(50,60,20)
df1['comp']=np.random.randint(50,65,20)
df1['ba']=np.random.randint(50,75,20)
df1['stats']=np.random.randint(50,70,20)
df1['chemistry']=np.random.randint(50,60,20)
df1['physics']=np.random.randint(40,60,20)
df1['history']=np.random.randint(60,70,20)
df1['politics']=np.random.randint(40,50,20)
df1['economics']=np.random.randint(50,70,20)
df1['english']=np.random.randint(45,50,20)
df1['biology']=np.random.randint(40,60,20)
df1['q4']=100
df1['q5']=0
df1['q6']=100
for x in ['q1','q2','q3','q7','q8','q9','q10','q11','q12','q13','q14','q15','q16','q17','q18']:
    df1[x]=0
    
df1['field']='Management'
df1['accounts']=np.random.randint(50,60,20)

In [76]:
df1=pd.DataFrame()
df1['maths']=np.random.randint(50,60,10)
df1['comp']=np.random.randint(50,65,10)
df1['ba']=np.random.randint(50,75,10)
df1['stats']=np.random.randint(50,70,10)
df1['chemistry']=np.random.randint(50,60,10)
df1['physics']=np.random.randint(40,60,10)
df1['history']=np.random.randint(60,70,10)
df1['politics']=np.random.randint(40,50,10)
df1['economics']=np.random.randint(50,70,10)
df1['english']=np.random.randint(45,50,10)
df1['biology']=np.random.randint(40,60,10)
df1['q4']=100
df1['q5']=100
df1['q6']=0
for x in ['q1','q2','q3','q7','q8','q9','q10','q11','q12','q13','q14','q15','q16','q17','q18']:
    df1[x]=0
    
df1['field']='Management'
df1['accounts']=np.random.randint(50,60,10)

In [77]:
management = pd.concat([management,df1])
management.shape

(350, 31)

In [78]:
final = pd.DataFrame()
final = pd.concat([technical,management])

/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


In [79]:
final.shape

(700, 31)

## Medical

In [97]:
df['maths']=np.random.randint(40,50,300)
df['comp']=np.random.randint(40,50,300)
df['ba']=np.random.randint(40,50,300)
df['stats']=np.random.randint(40,50,300)
df['chemistry']=np.random.randint(70,101,300)
df['physics']=np.random.randint(40,50,300)
df['history']=np.random.randint(40,50,300)
df['politics']=np.random.randint(40,50,300)
df['economics']=np.random.randint(40,50,300)
df['english']=np.random.randint(40,50,300)
df['biology']=np.random.randint(70,101,300)
df['accounts']=np.random.randint(50,60,300)
df['q7']=100
df['q8']=100
df['q2']=100
for x in ['q1','q3','q4','q5','q6','q9','q10','q11','q12','q13','q14','q15','q16','q17','q18']:
    df[x]=0
    
df['field']='Medical'

In [102]:
df1=pd.DataFrame()
df1['maths']=np.random.randint(50,60,10)
df1['comp']=np.random.randint(50,65,10)
df1['ba']=np.random.randint(50,75,10)
df1['stats']=np.random.randint(50,70,10)
df1['chemistry']=np.random.randint(50,60,10)
df1['physics']=np.random.randint(40,60,10)
df1['history']=np.random.randint(60,70,10)
df1['politics']=np.random.randint(40,50,10)
df1['economics']=np.random.randint(50,70,10)
df1['english']=np.random.randint(45,50,10)
df1['biology']=np.random.randint(40,60,10)
df1['q7']=100
df1['q8']=100
df1['q2']=0
for x in ['q1','q3','q4','q5','q6','q9','q10','q11','q12','q13','q14','q15','q16','q17','q18']:
    df1[x]=0
    
df1['field']='Medical'
df1['accounts']=np.random.randint(50,60,10)

In [103]:
medical = pd.concat([medical,df1])

/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


In [105]:
final.shape


(700, 31)

In [106]:
final = pd.concat([final,medical])

In [107]:
final.shape

(1050, 31)

## Convivialist

In [108]:
df['maths']=np.random.randint(40,50,300)
df['comp']=np.random.randint(40,50,300)
df['ba']=np.random.randint(40,50,300)
df['stats']=np.random.randint(40,50,300)
df['chemistry']=np.random.randint(70,101,300)
df['physics']=np.random.randint(40,50,300)
df['history']=np.random.randint(75,101,300)
df['politics']=np.random.randint(75,101,300)
df['economics']=np.random.randint(75,101,300)
df['english']=np.random.randint(40,50,300)
df['biology']=np.random.randint(70,101,300)
df['accounts']=np.random.randint(50,60,300)
df['q11']=100
df['q3']=100
df['q4']=100
for x in ['q1','q2','q5','q6','q7','q8','q9','q10','q12','q13','q14','q15','q16','q17','q18']:
    df[x]=0
    
df['field']='Convivialist'

In [115]:
df1=pd.DataFrame()
df1['maths']=np.random.randint(50,60,10)
df1['comp']=np.random.randint(50,65,10)
df1['ba']=np.random.randint(50,75,10)
df1['stats']=np.random.randint(50,70,10)
df1['chemistry']=np.random.randint(50,60,10)
df1['physics']=np.random.randint(40,60,10)
df1['history']=np.random.randint(60,70,10)
df1['politics']=np.random.randint(40,70,10)
df1['economics']=np.random.randint(50,70,10)
df1['english']=np.random.randint(45,50,10)
df1['biology']=np.random.randint(40,60,10)
df1['q11']=100
df1['q3']=100
df1['q4']=0
for x in ['q1','q2','q5','q6','q7','q8','q9','q10','q12','q13','q14','q15','q16','q17','q18']:
    df1[x]=0
    
df1['field']='Convivialist'
df1['accounts']=np.random.randint(50,60,10)

In [116]:
convivialist = pd.concat([convivialist,df1])

/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


In [117]:
convivialist.shape

(350, 31)

In [118]:
final = pd.concat([final,convivialist])

In [119]:
final.shape

(1400, 31)

In [183]:
final['field'].replace("Technical",1,inplace=True)
final['field'].replace("Management",2,inplace=True)
final['field'].replace("Medical",3,inplace=True)
final['field'].replace("Convivialist",4,inplace=True)
final['field'].replace("Artistic",5,inplace=True)
final['field'].replace("Teaching",6,inplace=True)

In [184]:
X=final.drop(['field'],1)
X=X.values
y=final['field']
y=y.values

In [186]:
import sklearn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
from sklearn import svm
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import accuracy_score

model = svm.SVC(kernel = "rbf")
model.fit(X_train, y_train)
pred_y = model.predict(X_test)
print(metrics.classification_report(y_test, pred_y))
print(metrics.confusion_matrix(y_test,pred_y))
print(accuracy_score(y_test, pred_y))
svm_score=accuracy_score(y_test, pred_y)

/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


              precision    recall  f1-score   support

           1       0.00      0.00      0.00       116
           2       0.00      0.00      0.00       125
           3       1.00      0.53      0.69       109
           4       0.36      1.00      0.53       226
           5       0.00      0.00      0.00        14
           6       1.00      0.03      0.06       103

    accuracy                           0.41       693
   macro avg       0.39      0.26      0.21       693
weighted avg       0.42      0.41      0.29       693

[[  0   0   0 116   0   0]
 [  0   0   0 125   0   0]
 [  0   0  58  51   0   0]
 [  0   0   0 226   0   0]
 [  0   0   0  14   0   0]
 [  0   0   0 100   0   3]]
0.41414141414141414


/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [187]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)
prediction = model.predict(X_test)

print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test,prediction))
print(accuracy_score(y_test, prediction))
accuracy_score(y_test,prediction)*100

              precision    recall  f1-score   support

           1       1.00      1.00      1.00       116
           2       1.00      1.00      1.00       125
           3       1.00      1.00      1.00       109
           4       1.00      0.96      0.98       226
           5       0.64      1.00      0.78        14
           6       1.00      1.00      1.00       103

    accuracy                           0.99       693
   macro avg       0.94      0.99      0.96       693
weighted avg       0.99      0.99      0.99       693

[[116   0   0   0   0   0]
 [  0 125   0   0   0   0]
 [  0   0 109   0   0   0]
 [  0   0   0 218   8   0]
 [  0   0   0   0  14   0]
 [  0   0   0   0   0 103]]
0.9884559884559885


98.84559884559884

## Artistic

In [ ]:
df['maths']=np.random.randint(40,50,300)
df['comp']=np.random.randint(40,50,300)
df['ba']=np.random.randint(60,101,300)
df['stats']=np.random.randint(70,101,300)
df['chemistry']=np.random.randint(40,55,300)
df['physics']=np.random.randint(40,50,300)
df['history']=np.random.randint(40,50,300)
df['politics']=np.random.randint(40,50,300)
df['economics']=np.random.randint(45,101,300)
df['english']=np.random.randint(70,101,300)
df['biology']=np.random.randint(40,50,300)
df['accounts']=np.random.randint(40,55,300)
df['q11']=100
df['q3']=100
df['q4']=100
for x in ['q1','q2','q5','q6','q7','q8','q9','q10','q12','q13','q14','q15','q16','q17','q18']:
    df[x]=0
    
df['field']='Artistic'

In [125]:
df1=pd.DataFrame()
df1['maths']=np.random.randint(50,60,20)
df1['comp']=np.random.randint(50,65,20)
df1['ba']=np.random.randint(50,55,20)
df1['stats']=np.random.randint(50,60,20)
df1['chemistry']=np.random.randint(50,60,20)
df1['physics']=np.random.randint(40,60,20)
df1['history']=np.random.randint(50,60,20)
df1['politics']=np.random.randint(40,50,20)
df1['economics']=np.random.randint(50,57,20)
df1['english']=np.random.randint(45,65,20)
df1['biology']=np.random.randint(40,60,20)
df1['q11']=100
df1['q3']=0
df1['q4']=100
for x in ['q1','q2','q5','q6','q7','q8','q9','q10','q12','q13','q14','q15','q16','q17','q18']:
    df1[x]=0
    
df1['field']='Artistic'
df1['accounts']=np.random.randint(50,60,20)

In [127]:
artistic=pd.concat([df,df1])
artistic.shape

/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


(320, 31)

In [128]:
df1=pd.DataFrame()
df1['maths']=np.random.randint(50,60,20)
df1['comp']=np.random.randint(50,65,20)
df1['ba']=np.random.randint(50,55,20)
df1['stats']=np.random.randint(50,60,20)
df1['chemistry']=np.random.randint(50,60,20)
df1['physics']=np.random.randint(40,60,20)
df1['history']=np.random.randint(50,60,20)
df1['politics']=np.random.randint(40,50,20)
df1['economics']=np.random.randint(50,57,20)
df1['english']=np.random.randint(45,65,20)
df1['biology']=np.random.randint(40,60,20)
df1['q11']=0
df1['q3']=100
df1['q4']=100
for x in ['q1','q2','q5','q6','q7','q8','q9','q10','q12','q13','q14','q15','q16','q17','q18']:
    df1[x]=0
    
df1['field']='Artistic'
df1['accounts']=np.random.randint(50,60,20)

In [129]:
artistic=pd.concat([artistic,df1])
artistic.shape

/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


(340, 31)

In [131]:
df1=pd.DataFrame()
df1['maths']=np.random.randint(50,60,10)
df1['comp']=np.random.randint(50,65,10)
df1['ba']=np.random.randint(50,55,10)
df1['stats']=np.random.randint(50,60,10)
df1['chemistry']=np.random.randint(50,60,10)
df1['physics']=np.random.randint(40,60,10)
df1['history']=np.random.randint(50,60,10)
df1['politics']=np.random.randint(40,50,10)
df1['economics']=np.random.randint(50,57,10)
df1['english']=np.random.randint(45,65,10)
df1['biology']=np.random.randint(40,60,10)
df1['q11']=100
df1['q3']=100
df1['q4']=0
for x in ['q1','q2','q5','q6','q7','q8','q9','q10','q12','q13','q14','q15','q16','q17','q18']:
    df1[x]=0
    
df1['field']='Artistic'
df1['accounts']=np.random.randint(50,60,10)

In [132]:
artistic=pd.concat([artistic,df1])
artistic.shape

/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


(350, 31)

In [133]:
#Teaching

In [146]:
df['maths']=np.random.randint(70,101,300)
df['comp']=np.random.randint(40,60,300)
df['ba']=np.random.randint(60,101,300)
df['stats']=np.random.randint(70,101,300)
df['chemistry']=np.random.randint(40,65,300)
df['physics']=np.random.randint(40,50,300)
df['history']=np.random.randint(40,57,300)
df['politics']=np.random.randint(40,55,300)
df['economics']=np.random.randint(45,101,300)
df['english']=np.random.randint(70,101,300)
df['biology']=np.random.randint(40,50,300)
df['accounts']=np.random.randint(40,55,300)
df['q12']=100
df['q5']=100
df['q10']=100
for x in ['q1','q2','q3','q4','q6','q7','q8','q9','q11','q13','q14','q15','q16','q17','q18']:
    df[x]=0
    
df['field']='Teaching'

/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


In [143]:
teaching.shape

(320, 31)

In [154]:
df1=pd.DataFrame()
df1['maths']=np.random.randint(50,60,20)
df1['comp']=np.random.randint(50,65,20)
df1['ba']=np.random.randint(50,55,20)
df1['stats']=np.random.randint(50,60,20)
df1['chemistry']=np.random.randint(50,60,20)
df1['physics']=np.random.randint(40,60,20)
df1['history']=np.random.randint(50,60,20)
df1['politics']=np.random.randint(40,50,20)
df1['economics']=np.random.randint(50,57,20)
df1['english']=np.random.randint(45,65,20)
df1['biology']=np.random.randint(40,60,20)
df1['q11']=100
df1['q3']=100
df1['q4']=0
for x in ['q1','q2','q3','q4','q6','q7','q8','q9','q11','q13','q14','q15','q16','q17','q18']:
    df1[x]=0
    
df1['field']='Teaching'
df1['accounts']=np.random.randint(50,60,20)

In [162]:
df1=pd.DataFrame()
df1['maths']=np.random.randint(50,60,10)
df1['comp']=np.random.randint(50,65,10)
df1['ba']=np.random.randint(50,55,10)
df1['stats']=np.random.randint(50,60,10)
df1['chemistry']=np.random.randint(50,60,10)
df1['physics']=np.random.randint(40,60,10)
df1['history']=np.random.randint(50,60,10)
df1['politics']=np.random.randint(40,50,10)
df1['economics']=np.random.randint(50,57,10)
df1['english']=np.random.randint(45,65,10)
df1['biology']=np.random.randint(40,60,10)
df1['q11']=100
df1['q3']=0
df1['q4']=100
for x in ['q1','q2','q3','q4','q6','q7','q8','q9','q11','q13','q14','q15','q16','q17','q18']:
    df1[x]=0
    
df1['field']='Teaching'
df1['accounts']=np.random.randint(50,60,10)

In [163]:
teaching=pd.concat([teaching,df1])
teaching.shape

/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


(350, 31)

In [164]:
teaching.shape

(350, 31)

In [169]:
artistic.shape

(350, 31)

In [171]:
final.groupby('field').count()

accounts   ba  biology  chemistry  comp  economics  english  history  \
field                                                                         
1           350  350      350        350   350        350      350      350   
2           350  350      350        350   350        350      350      350   
3           350  350      350        350   350        350      350      350   
4           350  350      350        350   350        350      350      350   

       maths  physics  ...  q18   q2   q3   q4   q5   q6   q7   q8   q9  stats  
field                  ...                                                      
1        350      350  ...  350  350  350  350  350  350  350  350  350    350  
2        350      350  ...  350  350  350  350  350  350  350  350  350    350  
3        350      350  ...  350  350  350  350  350  350  350  350  350    350  
4        350      350  ...  350  350  350  350  350  350  350  350  350    350  

[4 rows x 30 columns]

In [172]:
final = pd.concat([final,artistic,teaching])

In [173]:
final.shape

(2100, 31)

In [179]:
final['q5'].fillna(0,inplace=True)

In [302]:
final.isna().sum()

accounts     0
ba           0
biology      0
chemistry    0
comp         0
economics    0
english      0
field        0
history      0
maths        0
physics      0
politics     0
q1           0
q10          0
q11          0
q12          0
q13          0
q14          0
q15          0
q16          0
q17          0
q18          0
q2           0
q3           0
q4           0
q5           0
q6           0
q7           0
q8           0
q9           0
stats        0
dtype: int64

In [181]:
final.fillna(1,inplace=True)

In [189]:
f1=final

In [190]:
df1=pd.DataFrame()
df1['maths']=np.random.randint(40,60,30)
df1['comp']=np.random.randint(40,60,30)
df1['ba']=np.random.randint(40,60,30)
df1['stats']=np.random.randint(40,60,30)
df1['chemistry']=np.random.randint(40,60,30)
df1['physics']=np.random.randint(40,60,30)
df1['history']=np.random.randint(40,60,30)
df1['politics']=np.random.randint(40,60,30)
df1['economics']=np.random.randint(40,60,30)
df1['english']=np.random.randint(40,60,30)
df1['biology']=np.random.randint(40,60,30)
df1['q4']=0
df1['q5']=0
df1['q6']=0
for x in ['q1','q2','q3','q7','q8','q9','q10','q11','q12','q13','q14','q15','q16','q17','q18']:
    df1[x]=100
    
df1['field']=np.random.randint(1,7,30)
df1['accounts']=np.random.randint(50,60,30)

In [191]:
f1=pd.concat([df1,f1])

/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


In [284]:
f1=f1.drop(columns=['q13','q14','q15','q16','q17','q18'])

KeyError: "['q13' 'q14' 'q15' 'q16' 'q17' 'q18'] not found in axis"

In [352]:
X=f1.drop(['field'],1)
X=X.values
y=f1['field']
y=y.values

In [353]:
import sklearn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
from sklearn import svm
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import accuracy_score

model = svm.SVC(kernel = "rbf")
model.fit(X_train, y_train)
pred_y = model.predict(X_test)
print(metrics.classification_report(y_test, pred_y))
print(metrics.confusion_matrix(y_test,pred_y))
print(accuracy_score(y_test, pred_y))
svm_score=accuracy_score(y_test, pred_y)

/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00       182
         2.0       0.00      0.00      0.00       168
         3.0       1.00      0.03      0.07       177
         4.0       0.28      1.00      0.44       318
         5.0       0.00      0.00      0.00        78
         6.0       0.00      0.00      0.00       213

    accuracy                           0.29      1136
   macro avg       0.21      0.17      0.08      1136
weighted avg       0.23      0.29      0.13      1136

[[  0   0   0 182   0   0]
 [  0   0   0 168   0   0]
 [  0   0   6 171   0   0]
 [  0   0   0 318   0   0]
 [  0   0   0  78   0   0]
 [  0   0   0 213   0   0]]
0.2852112676056338


/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


df1=pd.DataFrame()
df1['maths']=np.random.randint(40,60,30)
df1['comp']=np.random.randint(40,60,30)
df1['ba']=np.random.randint(40,60,30)
df1['stats']=np.random.randint(40,60,30)
df1['chemistry']=np.random.randint(40,60,30)
df1['physics']=np.random.randint(40,60,30)
df1['history']=np.random.randint(40,60,30)
df1['politics']=np.random.randint(40,60,30)
df1['economics']=np.random.randint(40,60,30)
df1['english']=np.random.randint(40,60,30)
df1['biology']=np.random.randint(40,60,30)
df1['q1']=0
df1['q2']=0
df1['q3']=0
for x in ['q4','q5','q6','q7','q8','q9','q10','q11','q12']:
    df1[x]=100
    
df1['field']=np.random.randint(1,7,30)
df1['accounts']=np.random.randint(50,60,30)

In [241]:
f1=pd.concat([df1,f1])

/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


In [209]:
df1=pd.DataFrame()
df1['maths']=np.random.randint(40,60,30)
df1['comp']=np.random.randint(40,60,30)
df1['ba']=np.random.randint(40,60,30)
df1['stats']=np.random.randint(40,60,30)
df1['chemistry']=np.random.randint(40,60,30)
df1['physics']=np.random.randint(40,60,30)
df1['history']=np.random.randint(40,60,30)
df1['politics']=np.random.randint(40,60,30)
df1['economics']=np.random.randint(40,60,30)
df1['english']=np.random.randint(40,60,30)
df1['biology']=np.random.randint(40,60,30)
df1['q1']=0
df1['q2']=100
df1['q3']=0
df1['q4']=100
for x in ['q5','q6','q7','q8','q9','q10','q11','q12']:
    df1[x]=0
    
df1['field']=1
df1['accounts']=np.random.randint(50,60,30)

In [227]:
df1=pd.DataFrame()
df1['maths']=np.random.randint(40,60,300)
df1['comp']=np.random.randint(40,60,300)
df1['ba']=np.random.randint(40,60,300)
df1['stats']=np.random.randint(40,60,300)
df1['chemistry']=np.random.randint(40,60,300)
df1['physics']=np.random.randint(40,60,300)
df1['history']=np.random.randint(40,60,300)
df1['politics']=np.random.randint(40,60,300)
df1['economics']=np.random.randint(40,60,300)
df1['english']=np.random.randint(40,60,300)
df1['biology']=np.random.randint(40,60,300)

for x in ['q1','q2','q3','q4','q5','q6','q7','q8','q9','q10','q11','q12']:
    df1[x]=np.random.randint(0,101,300)
    
df1['field']=np.random.randint(1,7,300)
df1['accounts']=np.random.randint(50,60,300)

In [221]:
f1.shape

(2280, 25)

In [354]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)
prediction = model.predict(X_test)

print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test,prediction))
print(accuracy_score(y_test, prediction))
accuracy_score(y_test,prediction)*100

              precision    recall  f1-score   support

         1.0       0.81      0.68      0.74       182
         2.0       0.91      0.73      0.81       168
         3.0       0.88      0.59      0.71       177
         4.0       0.99      0.59      0.74       318
         5.0       0.18      0.96      0.30        78
         6.0       0.97      0.53      0.69       213

    accuracy                           0.64      1136
   macro avg       0.79      0.68      0.66      1136
weighted avg       0.88      0.64      0.71      1136

[[123   0   7   0  52   0]
 [  9 123   0   0  34   2]
 [ 14   0 105   0  57   1]
 [  0   2   5 188 123   0]
 [  1   0   1   1  75   0]
 [  5  10   1   0  84 113]]
0.6399647887323944


63.99647887323944

In [234]:
X.shape

(2100, 30)

In [350]:
df=pd.DataFrame()
df['maths']=np.random.randint(50,65,50)
df['comp']=np.random.randint(66,75,50)
df['ba']=np.random.randint(45,50,50)
df['stats']=np.random.randint(40,50,50)
df['chemistry']=np.random.randint(60,75,50)
df['physics']=np.random.randint(50,75,50)
df['history']=np.random.randint(55,60,50)
df['politics']=np.random.randint(45,50,50)
df['economics']=np.random.randint(40,50,50)
df['english']=np.random.randint(46,55,50)
df['biology']=np.random.randint(46,65,50)
df['accounts']=np.random.randint(40,50,50)
df['q4']=0
df['q5']=0
for x in ['q1','q2','q3','q6','q7','q8','q9','q10','q11','q12']:
    df[x]=np.random.randint(1,101,50)
    
df['field']=2

In [351]:
f1=pd.concat([f1,df])

/Users/shashankshivam/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


In [337]:
f1.drop(f1.isnull())

KeyError: "['accounts' 'ba' 'biology' 'chemistry' 'comp' 'economics' 'english'\n 'field' 'history' 'maths' 'physics' 'politics' 'q1' 'q10' 'q11' 'q12'\n 'q2' 'q3' 'q4' 'q5' 'q6' 'q7' 'q8' 'q9' 'stats'] not found in axis"

In [288]:
f1.shape

(3140, 25)

In [301]:
f1.shape

(3090, 25)

In [339]:
f2=f1.dropna(axis=0)

In [346]:
f1=f2

In [357]:
f1.to_csv('/Users/shashankshivam/Desktop/finalmarks.csv')